import type { Metadata } from 'next'
// import localFont from 'next/font/local'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import SessionProviderWrapper from '@/components/providers/SessionProvider'
import { Toaster } from '@/components/ui/toaster'
import ReactQueryProvider from '@/components/providers/react-query'
import { Session } from 'next-auth'

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// })

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { session, ...params },
}: Readonly<{
  children: React.ReactNode
  params: { session: Session }
}>) {
  return (
    <html lang='en'>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${poppins.className} min-h-screen`}
      >
        <SessionProviderWrapper session={session}>
          <ReactQueryProvider>
            <Navbar />
            {children}
            <Toaster />
          </ReactQueryProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
