"""Add certificates column in Candidate model

Revision ID: 601433c96a88
Revises: cc83890f3a9e
Create Date: 2024-09-22 13:55:19.780038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601433c96a88'
down_revision: Union[str, None] = 'cc83890f3a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('certificates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'certificates')
    # ### end Alembic commands ###
