"""Candidate Model: Add languages and extra curricular activities fields

Revision ID: bcc5adae93c3
Revises: 601433c96a88
Create Date: 2024-09-22 15:11:21.438384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc5adae93c3'
down_revision: Union[str, None] = '601433c96a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('languages', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('candidates', sa.Column('extracurricular', sa.String(), nullable=True))
    op.alter_column('candidates', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('candidates', 'extracurricular')
    op.drop_column('candidates', 'languages')
    # ### end Alembic commands ###
