"""Add Overview. Remove portofolio. Rename social_links to links.

Revision ID: cc83890f3a9e
Revises: 297d7688261d
Create Date: 2024-09-19 16:35:33.269480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc83890f3a9e'
down_revision: Union[str, None] = '297d7688261d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('overview', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('links', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('candidates', 'experience',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('candidates', 'social_links')
    op.drop_column('candidates', 'portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('portfolio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('social_links', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.alter_column('candidates', 'experience',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('candidates', 'links')
    op.drop_column('candidates', 'overview')
    op.drop_column('candidates', 'years_experience')
    # ### end Alembic commands ###
